-- ==========================================
-- Módulo de Nómina y Registro de Asistencia
-- Esquema: casa_bistro_analitica
-- ==========================================
-- IMPORTANTE: Ejecutar este script en el SQL Editor de Supabase
-- después de haber aplicado schema_roles.sql

-- 1. Tabla: employees (Empleados)
CREATE TABLE IF NOT EXISTS casa_bistro_analitica.employees (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    hourly_rate NUMERIC(10, 2) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE casa_bistro_analitica.employees ENABLE ROW LEVEL SECURITY;

-- Política: usuarios autenticados pueden leer empleados
DROP POLICY IF EXISTS "Usuarios autenticados pueden leer empleados" ON casa_bistro_analitica.employees;
CREATE POLICY "Usuarios autenticados pueden leer empleados"
  ON casa_bistro_analitica.employees FOR SELECT TO authenticated USING (true);

-- Política: solo admin puede crear/editar/desactivar empleados
-- (El control de admin se maneja en la app; RLS permite todo a autenticados por ahora)
DROP POLICY IF EXISTS "Usuarios autenticados pueden modificar empleados" ON casa_bistro_analitica.employees;
CREATE POLICY "Usuarios autenticados pueden modificar empleados"
  ON casa_bistro_analitica.employees FOR ALL TO authenticated USING (true);

GRANT ALL PRIVILEGES ON TABLE casa_bistro_analitica.employees TO anon, authenticated, service_role;

-- 2. Tabla: time_logs (Registro de Asistencia)
-- Regla de negocio: máximo 1 turno abierto por empleado por día
CREATE TABLE IF NOT EXISTS casa_bistro_analitica.time_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID NOT NULL REFERENCES casa_bistro_analitica.employees(id) ON DELETE CASCADE,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    check_in TIMESTAMPTZ NOT NULL DEFAULT now(),
    check_out TIMESTAMPTZ,
    total_minutes INTEGER,
    -- Restricción: solo un turno abierto (sin check_out) por empleado por día
    CONSTRAINT uq_one_open_shift_per_day UNIQUE NULLS NOT DISTINCT (employee_id, date, check_out)
);

ALTER TABLE casa_bistro_analitica.time_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios autenticados pueden leer time_logs" ON casa_bistro_analitica.time_logs;
CREATE POLICY "Usuarios autenticados pueden leer time_logs"
  ON casa_bistro_analitica.time_logs FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Usuarios autenticados pueden modificar time_logs" ON casa_bistro_analitica.time_logs;
CREATE POLICY "Usuarios autenticados pueden modificar time_logs"
  ON casa_bistro_analitica.time_logs FOR ALL TO authenticated USING (true);

GRANT ALL PRIVILEGES ON TABLE casa_bistro_analitica.time_logs TO anon, authenticated, service_role;

-- 3. Tabla: debts_and_advances (Deudas y Adelantos)
CREATE TABLE IF NOT EXISTS casa_bistro_analitica.debts_and_advances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID NOT NULL REFERENCES casa_bistro_analitica.employees(id) ON DELETE CASCADE,
    amount NUMERIC(12, 2) NOT NULL,
    description TEXT,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'DISCOUNTED')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE casa_bistro_analitica.debts_and_advances ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios autenticados pueden leer debts" ON casa_bistro_analitica.debts_and_advances;
CREATE POLICY "Usuarios autenticados pueden leer debts"
  ON casa_bistro_analitica.debts_and_advances FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "Usuarios autenticados pueden modificar debts" ON casa_bistro_analitica.debts_and_advances;
CREATE POLICY "Usuarios autenticados pueden modificar debts"
  ON casa_bistro_analitica.debts_and_advances FOR ALL TO authenticated USING (true);

GRANT ALL PRIVILEGES ON TABLE casa_bistro_analitica.debts_and_advances TO anon, authenticated, service_role;

-- 4. Tabla: payroll_liquidations (Liquidaciones Históricas — Inmutables)
CREATE TABLE IF NOT EXISTS casa_bistro_analitica.payroll_liquidations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id UUID NOT NULL REFERENCES casa_bistro_analitica.employees(id) ON DELETE CASCADE,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_minutes_worked INTEGER NOT NULL DEFAULT 0,
    hourly_rate_applied NUMERIC(10, 2) NOT NULL,
    gross_pay NUMERIC(12, 2) NOT NULL,
    total_deductions NUMERIC(12, 2) NOT NULL DEFAULT 0,
    net_pay NUMERIC(12, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE casa_bistro_analitica.payroll_liquidations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Usuarios autenticados pueden leer liquidaciones" ON casa_bistro_analitica.payroll_liquidations;
CREATE POLICY "Usuarios autenticados pueden leer liquidaciones"
  ON casa_bistro_analitica.payroll_liquidations FOR SELECT TO authenticated USING (true);

-- Las liquidaciones son inmutables: solo INSERT, no UPDATE ni DELETE
DROP POLICY IF EXISTS "Solo insertar liquidaciones" ON casa_bistro_analitica.payroll_liquidations;
CREATE POLICY "Solo insertar liquidaciones"
  ON casa_bistro_analitica.payroll_liquidations FOR INSERT TO authenticated WITH CHECK (true);

GRANT ALL PRIVILEGES ON TABLE casa_bistro_analitica.payroll_liquidations TO anon, authenticated, service_role;

-- ==========================================
-- Función y Trigger: Cálculo automático de minutos
-- ==========================================

CREATE OR REPLACE FUNCTION casa_bistro_analitica.calculate_total_minutes()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.check_out IS NOT NULL THEN
        NEW.total_minutes := EXTRACT(EPOCH FROM (NEW.check_out - NEW.check_in)) / 60;
    ELSE
        NEW.total_minutes := NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_calculate_total_minutes ON casa_bistro_analitica.time_logs;
CREATE TRIGGER trg_calculate_total_minutes
BEFORE INSERT OR UPDATE OF check_in, check_out
ON casa_bistro_analitica.time_logs
FOR EACH ROW
EXECUTE FUNCTION casa_bistro_analitica.calculate_total_minutes();
